FROM python:3.10

WORKDIR /app

COPY etl/requirements.txt .

RUN pip install --upgrade pip --no-cache-dir && \
    pip install -r requirements.txt --no-cache-dir

COPY etl/ .

# Используем shell-формат для CMD (более надежный в данном случае)
CMD python main.py